---
version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-stage:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozillastaging.cloud.looker.com/webhooks/projects/spoke-default/deploy
  deploy-dev:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilladev.cloud.looker.com/webhooks/projects/spoke-default/deploy
  sync-dashboards-prod:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: src/sync_dashboards/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python ./src/sync_dashboards/main.py lookml_dashboards.yaml
workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
      - deploy-stage:
          filters:
            branches:
              only: main-stage
            tags:
              only: /.*/
      - deploy-dev:
          filters:
            branches:
              only: main-nonprod
            tags:
              only: /.*/
      - sync-dashboards-prod:
          context: data-eng-looker
          requires:
            - deploy-prod
          filters:
            branches:
              only: main
            tags:
              only: /.*/
